### ISSUE TITLE
[FEATURE] Add Copier and Mover tests

### ISSUE THREAD

**Issue by zu1k** [beyondstorage/go-integration-test#26]
Could you please add Copier and Mover test cases?
Thanks!

**Comment by Xuanwo** [comment]
ping @JinnyYi to take a look.

**Comment by JinnyYi** [comment]
I have some questions:
- How to deal with directories for `Copy/Move`?
  When `cp/mv` a file/dir to an existing dir, the src file/dir will be copied or moved to be a sub file/dir of the dst. For object storage, wether the `dst` is an existing file or an existing directory is unkown for us(in the case of the dst is exist). Seems that the existing dst dir will be altered to the src file in the current implementation in `go-service-qingstor`.
- Is it necessary to check MD5 after `Copy/Move` successfully?
- `Copy Object Part` is unsupported for now, shell we only add copy object test first?

**Comment by Xuanwo** [comment]
> How to deal with directories for Copy/Move?

We don't know the ObjectMode of the dst path, so we don't need to deal with it. Just take the dst path as the final object path.

> Is it necessary to check MD5 after Copy/Move successfully?

We don't need to check hash in our service implementations. But we can implement a check in our tests. I think it's better to add a new issue to track it (other tests may need them too).

> Copy Object Part is unsupported for now, shell we only add copy object test first?

Yes, we only add copy/move object tests for now.
