### ISSUE TITLE
copy / move doesn't need to support dst path that has an existing path

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-integration-test#29]
https://github.com/beyondstorage/specs/issues/130#issuecomment-871956505

Maybe we could relax the restriction and leave this to further decision?

**Comment by Xuanwo** [comment]
ping @JinnyYi & @zu1k for discussion.

How about removing the tests about `When Copy to an existing file` and waiting for more feedback?

**Comment by zu1k** [comment]
Following the design of IPFS, I suggest returning a specific error like `ErrObjectAlreadyExist` and let the user decide whether to overwrite.

**Comment by Xuanwo** [comment]
> Following the design of IPFS, I suggest returning a specific error like `ErrObjectAlreadyExist` and let the user decide whether to overwrite.

Nice idea.

But other services may need a `stat` call to check whether the dst object exists. So I propose to:

1. remove this test case (which means don't include it as our formal behavior)
2. add an error code `ErrObjectExist` (or `ErrObjectAlreadyExist`) as we did on https://github.com/beyondstorage/go-storage/blob/master/services/error.go#L46 (we need a new GSP to add this error)
3. services like IPFS can return `ErrObjectExist` and leave this for a user to decide, services like s3 can always overwrite the dst without an extra API call.

<blockquote><img src="https://opengraph.githubassets.com/f2b32860cbe26f45490a7d0f7a9a44ee45705597d6ab14ca38be1c4aded401f1/beyondstorage/go-storage" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/beyondstorage/go-storage">beyondstorage/go-storage</a></strong></div><div>A unified storage layer for Golang, let's go beyond storage. - beyondstorage/go-storage</div></blockquote>

**Comment by zu1k** [comment]
We can add a pair like `force`, the caller should be clear whether they want to overwrite or avoid overwriting when performing the `copy/move` operation, by this parameter can avoid unnecessary `stat/delete` calls.

1. `force=true`: if the dst exists, for the service supporting overwriting, just overwrite; for the service not supporting overwriting, we should `delete` first.
2. `force=false`: if the dst exists, for the service returning `ErrObjectExist`, just return error; for the service not returning `ErrObjectExist`, we should `stat` first.

**Comment by Xuanwo** [comment]
> We can add a pair like `force`, the caller should be clear whether they want to overwrite or avoid overwriting when performing the `copy/move` operation, by this parameter can avoid unnecessary `stat` calls.

Let me think about it. With a `force` pair, we can have the following matrix.

| service / force | s3 | ipfs |
| - | - | - |
| true | N | Y |
| false | Y | N |

- If `force` is `false`, we still need a `stat` call for `s3` to return `ErrObjectExist` error.
- If `force` is `true`, and we need to call `FileRM` for `ipfs` though.

**Comment by Xuanwo** [comment]
In a word, adding `force` looks like can't resolve the problem we meet here. 

Call `stat` / `delete` in `copy` is not acceptable to me:

- The call adds extra overhead than native API.
- The call makes our `copy`/`move` as not atomic.

I prefer to let the user call the `stat`/`delete` by himself.

**Comment by zu1k** [comment]
If the behavior of the underlying service is followed, it is possible that the same operation may behave differently for the user on the upper layer using different backends, for example by returning unexpected errors, if the user has become accustomed to using a single backend.

It would be more in line with my expectations if I could rely on the upper layer in go-storage for behavior specification, providing predictable behavior through `force`, and expose the underlying interface to users who need performance.

As for atomicity, users calling multiple interfaces individually may also have this problem, and here it is just a matter of exposing the atomicity to the user or hiding it internally.

**Comment by Xuanwo** [comment]
> If the behavior of the underlying service is followed, it is possible that the same operation may behave differently for the user on the upper layer using different backends, for example by returning unexpected errors, if the user has become accustomed to using a single backend.
> 
> It would be more in line with my expectations if I could rely on the upper layer in go-storage for behavior specification, providing predictable behavior through `force`, and expose the underlying interface to users who need more performance.
> 
> As for atomicity, users calling multiple interfaces individually may also have this problem, and here it is just a matter of exposing the atomicity to the user or hiding it internally.

Nice catch. What you said makes sense.

Now, I think we need a GSP to normal the behavior of copy & move, in that GSP, we need to discuss / design:

- What's the behavior of `copy` & `move`? And how to implement them?
- Should we need to add a `force` pair?
- What's an error we should return if the dst path exists.
- ...

And before the GSP been accepted, we need to remove the test case `When Copy to an existing file` to avoid more problems.

---

Does this plan look good to you? @zu1k

**Comment by zu1k** [comment]
> Does this plan look good to you? @zu1k

YES! It does require careful consideration.

**Comment by Xuanwo** [comment]
> YES! It does require careful consideration.

Nice, now we're in agreement.

Ping @JinnyYi for more comments.

**Comment by Xuanwo** [comment]
#30 has been merged, and let's keep this issue open until relating GSP got approved.

**Comment by JinnyYi** [comment]
Maybe the confusion only caused by `copy`  in `ipfs`? 

![image](https://user-images.githubusercontent.com/82445294/124095227-0ccd7480-da8c-11eb-810a-c703fe701346.png)

I'm not sure whether there are OS-specific or service restrictions may apply to `move`.

**Comment by JinnyYi** [comment]
For atomicity, we have the similar problem in `delete` for `dropbox`(https://github.com/beyondstorage/go-service-dropbox/blob/master/storage.go#L135) and we leave this to users to make sure `only delete one object`.

For behavioral consistency, we have [Idempotent Storager Delete Operation](https://github.com/beyondstorage/specs/blob/master/rfcs/46-idempotent-delete.md) to make `delete` operation idempotent.

I think "add a pair like `force`" and "leave the related err for users to decide" are the tradeoff between behavior consistency and atomicity and both are OK to me.

<blockquote><img src="https://opengraph.githubassets.com/b79abea3a2e2a49ec4d25deccc1bc63c6705054fb30165d37933c896172be2cc/beyondstorage/go-service-dropbox" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/beyondstorage/go-service-dropbox">beyondstorage/go-service-dropbox</a></strong></div><div>Dropbox support for go-storage. Contribute to beyondstorage/go-service-dropbox development by creating an account on GitHub.</div></blockquote>

**Comment by Xuanwo** [comment]
Tracked in https://github.com/beyondstorage/go-storage/issues/624
